using System;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Philips.CodeAnalysis.Common;
using Philips.CodeAnalysis.MaintainabilityAnalyzers;

namespace Philips.CodeAnalysis.Test
{
	[TestClass]
	public class CopyrightPresentAnalyzerTest : DiagnosticVerifier
	{
		#region Non-Public Data Members

		private const string ExpectedFixedHeader = @"#region Header
// ©
#endregion
";

		#endregion

		#region Non-Public Properties/Methods

		protected override DiagnosticAnalyzer GetCSharpDiagnosticAnalyzer()
		{
			return new CopyrightPresentAnalyzer();
		}

		#endregion

		#region Public Interface

		[DataRow(@"#region H
			#endregion", false, 3)]
		[DataRow(@"#region Header
#endregion", false, 3)]
		[DataRow(@"#region Header
// ©
#endregion", true, -1)]
		[DataRow(@"// ©", true, -1)]
		[DataRow(@"/* ©", true, -1)]
		[DataRow(@"// Copyright", true, -1)]
		[DataRow(@"/* Copyright", true, -1)]
		[DataRow(@"", false, 2)]
		[DataTestMethod]
		public void HeaderIsDetected(string content, bool isGood, int errorLine)
		{
			string baseline = @"{0}
using Microsoft.VisualStudio.TestTools.UnitTesting;
class Foo 
{{
  public void Foo()
  {{
  }}
}}
";
			string givenText = string.Format(baseline, content);

			DiagnosticResult[] expected;

			if (isGood)
			{
				expected = Array.Empty<DiagnosticResult>();
			}
			else
			{
				expected = new[] { new DiagnosticResult
				{
					Id = Helper.ToDiagnosticId(DiagnosticIds.CopyrightPresent),
					Message = new Regex(".+"),
					Severity = DiagnosticSeverity.Error,
					Locations = new[]
					{
					new DiagnosticResultLocation("Test0.cs", errorLine, 1)
				} }
				};
			}

			VerifyCSharpDiagnostic(givenText, expected);
		}

		[DataRow(@"")]
		[DataRow(@"
")]
		[TestMethod]
		public void EmptyUnitIsIgnored(string text)
		{
			DiagnosticResult[] expected = Array.Empty<DiagnosticResult>();

			VerifyCSharpDiagnostic(text, expected);
		}


		[DataRow(@"// ------
// <auto-generated>
// content
// </auto-generated>
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute()]
", "blah")]
		[DataRow(@"// <auto-generated>
// content
// </auto-generated>
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute()]
", "blah")]
		[DataRow(@"// <auto-generated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute()]
", "blah")]
		[DataRow(@"// <autogenerated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute()]
", "blah")]
		[DataRow(@"using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute()]
", "AssemblyInfo")]
		[DataRow(@"using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute()]
", "Foo.AssemblyInfo")]
		[DataRow(@"using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute()]
", "Blah.Designer")]
		[DataTestMethod]
		public void AutogeneratedIsIgnored(string text, string filenamePrefix)
		{
			DiagnosticResult[] expected = Array.Empty<DiagnosticResult>();

			VerifyCSharpDiagnostic(text, filenamePrefix, expected);
		}


		[DataRow(@"Foo.Designer.cs")]
		[DataRow(@"Foo.designer.cs")]
		[DataTestMethod]
		public void IsGeneratedCaseAgnostic(string text)
		{
			Assert.IsTrue(Helper.IsGeneratedCode(text));
		}

		#endregion
	}
}
