name: Changelog
on:
  workflow_call:
    inputs:
      changelog:
        type: string
        required: true
      ref:
        type: string
        required: false

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ inputs.ref }}
    
      - name: Write Changelog
        if: ${{ inputs.changelog }}
        run: |
          CHANGELOG=""
          if [ -e CHANGELOG.md ]
          then
              CHANGELOG=$(cat CHANGELOG.md)
          fi
          echo -e "${{ inputs.changelog }}\n\n${CHANGELOG}" > CHANGELOG.md
          
          cat CHANGELOG.md
          
      - name: "Commit"
        if: ${{ inputs.changelog }}
        uses: EndBug/add-and-commit@cc9c08ba6c8df3b93a8f2db63e89b98368ae2ae8 # v11.1.1
        with:
          message: "chore: updating changelog"
          push: true
