name: Dogfood

on:
  workflow_call:
      
jobs:
  build:
    runs-on: ubuntu-latest
    name: Dogfood Analyzers
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Setup .NET Core
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2
        with:
          dotnet-version: |
            7.0.x

      - name: Build the Dogfood
        run: |
          cat > ./Directory.Build.props << 'EOF'
          <Project>
            <PropertyGroup>
              <PackageId>$(MSBuildProjectName).Dogfood</PackageId>
            </PropertyGroup>
          </Project>
          EOF
          dotnet build --configuration Release

      - name: Prepare to eat Dogfood
        run: |
          dotnet nuget add source $GITHUB_WORKSPACE/Packages
          rm -f ./Directory.Build.props
          cat > ./Directory.Build.props << EOF
          <Project>
            <PropertyGroup>
              <FileVersion>1.0.0</FileVersion>
            </PropertyGroup>
            <ItemGroup>
              <PackageReference Include="Philips.CodeAnalysis.MaintainabilityAnalyzers.Dogfood" Version="1.0.0">
                <PrivateAssets>all</PrivateAssets>
                <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
              </PackageReference>
              <PackageReference Include="Philips.CodeAnalysis.DuplicateCodeAnalyzer.Dogfood" Version="1.0.0">
                <PrivateAssets>all</PrivateAssets>
                <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
              </PackageReference>
              <PackageReference Include="Philips.CodeAnalysis.SecurityAnalyzers.Dogfood" Version="1.0.0">
                <PrivateAssets>all</PrivateAssets>
                <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
              </PackageReference>
              <PackageReference Include="Philips.CodeAnalysis.MsTestAnalyzers.Dogfood" Version="1.0.0">
                <PrivateAssets>all</PrivateAssets>
                <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
              </PackageReference>
              <PackageReference Include="Philips.CodeAnalysis.MoqAnalyzers.Dogfood" Version="1.0.0">
                <PrivateAssets>all</PrivateAssets>
                <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
              </PackageReference>
            </ItemGroup>
          </Project>
          EOF

      - name: Eat the Dogfood
        run: |
          dotnet build ./Philips.CodeAnalysis.Common/Philips.CodeAnalysis.Common.csproj --configuration Debug --framework netstandard2.0 -consoleloggerparameters:NoSummary -verbosity:quiet
          dotnet build ./Philips.CodeAnalysis.DuplicateCodeAnalyzer/Philips.CodeAnalysis.DuplicateCodeAnalyzer.csproj --configuration Debug --framework netstandard2.0 -consoleloggerparameters:NoSummary -verbosity:quiet
          dotnet build ./Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj --configuration Debug --framework netstandard2.0 -consoleloggerparameters:NoSummary -verbosity:quiet
          dotnet build ./Philips.CodeAnalysis.MoqAnalyzers/Philips.CodeAnalysis.MoqAnalyzers.csproj --configuration Debug --framework netstandard2.0 -consoleloggerparameters:NoSummary -verbosity:quiet
          dotnet build ./Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj --configuration Debug --framework netstandard2.0 -consoleloggerparameters:NoSummary -verbosity:quiet
          dotnet build ./Philips.CodeAnalysis.SecurityAnalyzers/Philips.CodeAnalysis.SecurityAnalyzers.csproj --configuration Debug --framework netstandard2.0 -consoleloggerparameters:NoSummary -verbosity:quiet
          dotnet build ./Philips.CodeAnalysis.Test/Philips.CodeAnalysis.Test.csproj --configuration Debug --framework net7.0 -consoleloggerparameters:NoSummary -verbosity:quiet
          dotnet build ./Philips.CodeAnalysis.Benchmark/Philips.CodeAnalysis.Benchmark.csproj --configuration Debug --framework net7.0 -consoleloggerparameters:NoSummary -verbosity:quiet
          dotnet build ./Philips.CodeAnalysis.AnalyzerPerformance/Philips.CodeAnalysis.AnalyzerPerformance.csproj --configuration Debug --framework net7.0 -consoleloggerparameters:NoSummary -verbosity:quiet
