name: Pinned Actions
on:
  workflow_call:
jobs:
  pinned_actions:
    name: Pin GitHub Actions to SHA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
        
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@70c4af2ed5282c51ba40566d026d6647852ffa3e # ratchet:zgosalvez/github-actions-ensure-sha-pinned-actions@v5.0.1
        with:
          allowlist: philips-software/roslyn-analyzers
