name: Pinned Actions
on:
  workflow_call:
jobs:
  pinned_actions:
    name: Pin GitHub Actions to SHA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
        
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@ca46236c6ce584ae24bc6283ba8dcf4b3ec8a066 # ratchet:zgosalvez/github-actions-ensure-sha-pinned-actions@v5.0.4
        with:
          allowlist: philips-software/roslyn-analyzers
