name: Prepare for Release
on:
  workflow_dispatch:
jobs:
  tagversion:
    uses: ./.github/workflows/tagversion.yml

  branch:
    needs: tagversion
    runs-on: ubuntu-latest
    steps:
    - name: Create Branch
      id: create-branch
      uses: peterjgrainger/action-create-branch@c2800a3a9edbba2218da6861fa46496cf8f3195a # @v2.2.0
      with:
        branch: 'release-${{ needs.tagversion.outputs.new_version }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  changelog:
    needs: [tagversion, branch]
    uses: ./.github/workflows/changelog.yml
    with:
      changelog: ${{ needs.tagversion.outputs.changelog }}
      ref: release-${{ needs.tagversion.outputs.new_version }}

  pr:
    needs: changelog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # @v1
    
    - name: Create Pull Request
      if: steps.create-branch.outputs.created
      run: gh pr create -B 'main' -H 'release-${{ needs.tagversion.outputs.new_version }}' --title 'Release ${{ needs.tagversion.outputs.new_version }}' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

