name: Prepare for Release
on:
  workflow_dispatch:
jobs:
  tagversion:
    uses: ./.github/workflows/tagversion.yml

  branch:
    needs: tagversion
    runs-on: ubuntu-latest
    steps:
    - name: Create Branch
      id: create-branch
      uses: peterjgrainger/action-create-branch@c2800a3a9edbba2218da6861fa46496cf8f3195a # @v2.2.0
      with:
        branch: 'release/${{ needs.tagversion.outputs.new_version }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      if: steps.create-branch.outputs.created
      uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # @v6.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Release ${{ needs.tagversion.outputs.new_version }}',
            head: 'release/${{ needs.tagversion.outputs.new_version }}',
            base: 'main',
            debug: true
          })

