name: Publish

on:
  workflow_call:
    inputs:
      new_tag:
        type: string
        required: true
    secrets:
      nuget-token:
        required: true
        
jobs:
  publish:
    strategy:
      matrix:
        package: [MaintainabilityAnalyzers, DuplicateCodeAnalyzer, MoqAnalyzers, MsTestAnalyzers]
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    
    - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 #v4.0.2
      id: changes
      with:
        filters: |
          ${{ matrix.package }}:
            - 'Philips.CodeAnalysis.${{ matrix.package }}/**'
            
    - name: Download artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v5
      with:
        name: Philips.CodeAnalysis.${{ matrix.package }}-${{ inputs.new_tag }}

    - name: Nuget
      if: (steps.changes.outputs.MaintainabilityAnalyzers == 'true' && matrix.package == 'MaintainabilityAnalyzers') || (steps.changes.outputs.DuplicateCodeAnalyzer == 'true' && matrix.package == 'DuplicateCodeAnalyzer') || (steps.changes.outputs.MoqAnalyzers == 'true' && matrix.package == 'MoqAnalyzers') || (steps.changes.outputs.MsTestAnalyzers == 'true' && matrix.package == 'MsTestAnalyzers') || (steps.changes.outputs.SecurityAnalyzers == 'true' && matrix.package == 'SecurityAnalyzers')
      run: |
        echo Publishing to Nuget Philips.CodeAnalysis.${{ matrix.package }}.${{ inputs.new_tag }}.*.nupkg >> $GITHUB_STEP_SUMMARY
        echo Publishing to Nuget Philips.CodeAnalysis.${{ matrix.package }}.${{ inputs.new_tag }}.*.snupkg >> $GITHUB_STEP_SUMMARY
#        dotnet nuget push Philips.CodeAnalysis.${{ matrix.package }}.${{ inputs.new_tag }}.*.nupkg --api-key ${{ secrets.nuget-token }} --source https://api.nuget.org/v3/index.json
#        dotnet nuget push Philips.CodeAnalysis.${{ matrix.package }}.${{ inputs.new_tag }}.*.snupkg --api-key ${{ secrets.nuget-token }} --source https://api.nuget.org/v3/index.json
