name: Release
on:
  workflow_call:
    inputs:
      new_tag:
        type: string
        required: false
      changelog:
        type: string
        required: false
      prerelease:
        type: boolean
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d #v4.0.1
      id: changes
      with:
        filters: |
          packages:
            - 'Philips.CodeAnalysis.MaintainabilityAnalyzers/**'
            - 'Philips.CodeAnalysis.DuplicateCodeAnalyzer/**'
            - 'Philips.CodeAnalysis.MoqAnalyzers/**'
            - 'Philips.CodeAnalysis.MaintainabilityAnalyzers/**'
            - 'Philips.CodeAnalysis.MsTestAnalyzers/**'
            - 'Philips.CodeAnalysis.SecurityAnalyzers/**'
          
    - name: GitHub Tag & Release
#      if: steps.changes.outputs.packages == 'true'
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd #v1.20
      with:
        tag: ${{ inputs.new_tag }}
        name: Release ${{ inputs.new_tag }}
        body: ${{ inputs.changelog }}
        prerelease: ${{ inputs.prerelease }}
        allowUpdates: true
        generateReleaseNotes: true
        commit: ${{ github.sha }}
