name: Release
on:
  workflow_call:
    inputs:
      new_tag:
        type: string
        required: false
      changelog:
        type: string
        required: false
      prerelease:
        type: boolean
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 #v4.0.2
      id: changes
      with:
        filters: |
          packages:
            - 'Philips.CodeAnalysis.MaintainabilityAnalyzers/**'
            - 'Philips.CodeAnalysis.DuplicateCodeAnalyzer/**'
            - 'Philips.CodeAnalysis.MoqAnalyzers/**'
            - 'Philips.CodeAnalysis.MaintainabilityAnalyzers/**'
            - 'Philips.CodeAnalysis.MsTestAnalyzers/**'
            - 'Philips.CodeAnalysis.SecurityAnalyzers/**'
          
    - name: GitHub Tag & Release
#      if: steps.changes.outputs.packages == 'true'
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd #v1.20
      with:
        tag: ${{ inputs.new_tag }}
        name: Release ${{ inputs.new_tag }}
        body: ${{ inputs.changelog }}
        prerelease: ${{ inputs.prerelease }}
        allowUpdates: true
        generateReleaseNotes: true
        commit: ${{ github.sha }}
